Next value: 1
Exception: error
Finally
